  #Create SG resource 
Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Allow SSH and HTTP from Public Space
      GroupName: CFSecurityGroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22 
          CidrIp: 0.0.0.0/0
#Importing Value that was Outputted from VPC-Scott stack for the VPC ID           
      VpcId: !ImportValue VPC-Scott-VPC

Outputs: 
  SGOutput:
    Description: Security Group ID
    Value: !Ref SecurityGroup
    Export: 
      Name: !Sub ${AWS::StackName}-SecurityGroup 

